export const MODAL_OPEN = "MODAL_OPEN";
export const TOKEN_MODAL_OPEN = "TOKEN_MODAL_OPEN";

export const ADMIN_SELECTED = "ADMIN_SELECTED";

export const ADMIN_FETCH_REQUESTED = "ADMIN_FETCH_REQUESTED";
export const ADMIN_FETCH_SUCCEEDED = "ADMIN_FETCH_SUCCEEDED";
export const ADMIN_FETCH_FAILED = "ADMIN_FETCH_FAILED";

export const ADMIN_ADD_REQUESTED = "ADMIN_ADD_REQUESTED";
export const ADMIN_ADD_SUCCEEDED = "ADMIN_ADD_SUCCEEDED";
export const ADMIN_ADD_FAILED = "ADMIN_ADD_FAILED";

export const ADMIN_UPDATE_REQUESTED = "ADMIN_UPDATE_REQUESTED";
export const ADMIN_UPDATE_SUCCEEDED = "ADMIN_UPDATE_SUCCEEDED";
export const ADMIN_UPDATE_FAILED = "ADMIN_UPDATE_FAILED";

export const ADMIN_DELETE_REQUESTED = "ADMIN_DELETE_REQUESTED";
export const ADMIN_DELETE_SUCCEEDED = "ADMIN_DELETE_SUCCEEDED";
export const ADMIN_DELETE_FAILED = "ADMIN_DELETE_FAILED";
